package com.youngkke.careon.domain.carer.dto;

/** PATCH /api/web/users/me/diagnosis-profile 요청 body. 모든 필드 optional (보낸 필드만 수정). */
public record DiagnosisProfileRequest(
        Integer age,
        Integer householdMembersCount,
        Integer caredCount,
        String knowHousingType,
        String housingType,
        String biggestBurdenType,
        String burdenTypeReasonSummary,
        String dailyCareHoursSelf,
        String dailyCareHoursHousehold,
        Boolean hasBackupCaregiver,
        String backupCaregiverRelation,
        String medicalBurdenLevel,
        Boolean isStudent,
        Boolean hasIncomeActivity,
        String incomeValueStatus,
        String incomeAssessmentCriteria,
        Integer incomeValue,
        String medianIncomeRatio,
        String incomeVariabilityType,
        String incomeRelatedUtterance,
        Boolean hasBasicLivelihoodSupport,
        Boolean hasBasicLivelihoodSupportSource,
        Boolean hasChaSangWi,
        Boolean hasChaSangWiSource,
        String militaryServiceStatus,
        Integer militaryServiceExtensionYears,
        Integer housingDeposit,
        Integer housingMonthlyRent,
        Integer householdAssetValue,
        Integer vehicleValue,
        String financialDetailStatus) {}
